sonar.projectKey=openremote_console-ios-lib
sonar.organization=openremote
sonar.sources=ORLib
sonar.tests=Tests
sonar.sourceEncoding=UTF-8
sonar.swift.swiftLint.reportPaths=swiftlint.json
sonar.coverageReportPaths=Coverage.xml
